apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bridge-machine-service-maintenance-kafka
  description: bridge machine service maintenance kafka
spec:
  type: asyncapi
  owner: vlad
  lifecycle: production
  definition: 
    $text: ./contract.yml
